version: "3.1"

services: 
  database:
    build: 
      context: ./database
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER_FILE: /run/secrets/secret_database_user
      POSTGRES_PASSWORD_FILE: /run/secrets/secret_database_password
      POSTGRES_DB_FILE: /run/secrets/secret_database_db
    secrets:
      - secret_database_user
      - secret_database_password
      - secret_database_db
    volumes:
      - volume_database:/var/lib/postgresql/data
    networks:
      - webnetwork

networks:
  webnetwork:

volumes:
  volume_database:

secrets:
  secret_database_password:
    file: ./secrets/secret_database_password
  secret_database_user:
    file: ./secrets/secret_database_user
  secret_database_db:
    file: ./secrets/secret_database_db
